//
//	image.h
//	New Image
//
//	Created by Robert Spychala on 7/25/10
//	Copyright 2010 VisiScience, Inc.
//	This code was generated by Opacity. You may use or modify it in any way.
//

#import <UIKit/UIKit.h>

extern const CGFloat kMyViewWidth;
extern const CGFloat kMyViewHeight;

@interface Badge : UIView {
 
    NSNumber *count;
}

@property (nonatomic, retain) NSNumber *count;

@end
